### ISSUE TITLE
Composer Problem

### ISSUE THREAD

**Issue by surfer190** [BitolaCo/php-geoip-check#1]
Problem 1
    - Installation request for ext-geoip 1.0.8 -> satisfiable by ext-geoip[1.0.8].
    - geoip/geoip v1.14 conflicts with ext-geoip[1.0.8].
    - Installation request for geoip/geoip v1.14 -> satisfiable by geoip/geoip[v1.14].

**Comment by ChunkRadius** [comment]
Thanks for the report. Will check it out! We haven't used this package in a bit, and it probably needs a bit of tlc :smile:

**Comment by karen-mikaela** [comment]
Hi @bradberger , the same problem here. Any updates?
Tks.

**Comment by ChunkRadius** [comment]
@karen-mikaela @surfer190 Hey guys, sorry for the delay. Should be installable now. Tried it here on Ubuntu, and everything's working. Let me know if you are still having issues.

The name of the package was out of date, as well, so you'll now find it at [bitolaco/geoipcheck](https://packagist.org/packages/bitolaco/geoipcheck). Also switched to requiring the default PHP geoip extension, for what it's worth.

**Comment by karen-mikaela** [comment]
Thank you @bradberger . I just installed bitolaco/geoipcheck (v0.1.1) om Ubuntu too. It is works.
